services:
  armada-assault:
    # build: ./ArmadaAssault
    image: ghcr.io/corsaircoalition/armadaassault:latest
    command: ["attack", "explore", "spread"]
    volumes:
      - ./config.json:/config.json
    links:
      - redis
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  sergeant-socket:
    # build: ./SergeantSocket
    image: ghcr.io/corsaircoalition/sergeantsocket:latest
    volumes:
      - ./config.json:/config.json
    links:
      - redis

  strategy-sentinel:
    # build: ./StrategySentinel
    image: ghcr.io/corsaircoalition/strategysentinel:latest
    volumes:
      - ./config.json:/config.json
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  commander-cortex:
    profiles:
      - ui
    # build: ./CommanderCortex
    image: ghcr.io/corsaircoalition/commandercortex:latest
    volumes:
      - ./config.json:/config.json
    links:
      - redis
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    stdin_open: true
    tty: true

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
