services:
  armada-assault:
    # build: ./ArmadaAssault
    image: ghcr.io/corsaircoalition/armadaassault:latest
    command: ["attack", "explore", "spread"]
    volumes:
      - ./config.json:/config.json
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""

  sergeant-socket:
    # build: ./SergeantSocket
    image: ghcr.io/corsaircoalition/sergeantsocket:latest
    volumes:
      - ./config.json:/config.json
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""

  strategy-sentinel:
    # build: ./StrategySentinel
    image: ghcr.io/corsaircoalition/strategysentinel:latest
    volumes:
      - ./config.json:/config.json
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""

  commander-cortex:
    profiles:
      - ui
    # build: ./CommanderCortex
    image: ghcr.io/corsaircoalition/commandercortex:latest
    volumes:
      - ./config.json:/config.json
    depends_on:
      - redis
      - sergeant-socket
      - strategy-sentinel
      - armada-assault
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
    stdin_open: true
    tty: true

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
