services:
  armada-assault:
    build: ./ArmadaAssault
    # image: ghcr.io/corsaircoalition/armadaassault:2
    # command: ["--debug", "attack", "explore", "spread"]
    command: ["attack", "explore", "spread"]
    volumes:
      - ./config.json:/config.json
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""

  sergeant-socket:
    build: ./SergeantSocket
    # image: ghcr.io/corsaircoalition/sergeantsocket:3
    # command: ["--debug"]
    volumes:
      - ./config.json:/config.json
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      AUTH_TOKEN: sd09fjd203i0ejwi

  strategy-sentinel:
    build: ./StrategySentinel
    # image: ghcr.io/corsaircoalition/strategysentinel:1
    # command: ["--debug"]
    volumes:
      - ./config.json:/config.json
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""

  commander-cortex:
    profiles:
      - ui
    image: ghcr.io/corsaircoalition/commandercortex:1
    # command: ["--debug"]
    volumes:
      - ./config.json:/config.json
    depends_on:
      - redis
      - sergeant-socket
      - strategy-sentinel
      - armada-assault
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
    stdin_open: true
    tty: true

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
