services:

  # Define the Redis service and expose Redis' default port on localhost
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Define the Flobot service
  flobot:
    container_name: flobot
    image: ghcr.io/corsaircoalition/flobot:latest
    volumes:
      - ./config.flobot.json:/config.json # configure Flobot to use config.flobot.json
    depends_on:
      - redis
    command: ["-n", "5"] # instruct Flobot to play 5 games
    environment: # use environment variables to override the values in config.json
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TLS: false
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
